// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

import 'package:dartastic_opentelemetry_api/src/api/id/id_generator.dart';
import 'package:test/test.dart';

void main() {
  group('IdGenerator', () {
    test('generates valid trace ID', () {
      final bytes = IdGenerator.generateTraceId();
      expect(bytes.length, equals(16));
      expect(IdGenerator.bytesToHex(bytes).length, equals(32));

      // Verify not all zeros
      expect(bytes.any((b) => b != 0), isTrue);
    });

    test('generates valid span ID', () {
      final bytes = IdGenerator.generateSpanId();
      expect(bytes.length, equals(8));
      expect(IdGenerator.bytesToHex(bytes).length, equals(16));

      // Verify not all zeros
      expect(bytes.any((b) => b != 0), isTrue);
    });

    test('converts bytes to hex', () {
      final bytes = [0x12, 0x34, 0xAB, 0xCD];
      expect(IdGenerator.bytesToHex(bytes), equals('1234abcd'));
    });

    test('converts hex to bytes', () {
      final hex = '1234abcd';
      final bytes = IdGenerator.hexToBytes(hex);
      expect(bytes, equals([0x12, 0x34, 0xAB, 0xCD]));
    });

    // IDs come from a locally expanded PRNG seeded once from the OS CSPRNG
    // (see the _Prng doc comment in id_generator.dart for the rationale).
    // These tests guard the properties the W3C Trace Context spec actually
    // requires of generated IDs: non-zero and globally unique in practice.
    group('uniqueness', () {
      test('10k span IDs are all distinct', () {
        final seen = <String>{};
        for (var i = 0; i < 10000; i++) {
          final id = IdGenerator.bytesToHex(IdGenerator.generateSpanId());
          expect(seen.add(id), isTrue, reason: 'duplicate span ID: $id');
        }
      });

      test('2k trace IDs are all distinct', () {
        final seen = <String>{};
        for (var i = 0; i < 2000; i++) {
          final id = IdGenerator.bytesToHex(IdGenerator.generateTraceId());
          expect(seen.add(id), isTrue, reason: 'duplicate trace ID: $id');
        }
      });

      test('generated bytes are not confined to a subset of the byte range',
          () {
        // The generator must use the whole byte range; a broken
        // implementation that, say, emitted only ASCII or zero-padded
        // would shrink the ID space and raise real collision risk.
        final values = <int>{};
        for (var i = 0; i < 128; i++) {
          values.addAll(IdGenerator.generateSpanId());
        }
        expect(values.length, greaterThan(200));
      });
    });

    test('returns null for invalid hex string', () {
      expect(IdGenerator.hexToBytes('invalid'), isNull);
      expect(IdGenerator.hexToBytes('123'), isNull);
    });
  });
}
